name: github-actions
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry testresources
          make install
      - name: Run linter
        run: make lint
